### ISSUE TITLE
Server crash in mesecons_detector

### ISSUE THREAD

**Issue by vitaminx** [Jeija/minetest-mod-mesecons#224] opened 2015-02-16 10:59 UTC
Hi, my server crashed 5 times in just a couple of minutes today:

    07:35:53: ERROR[main]: ERROR: An unhandled exception occurred: /usr/share/games/minetest/builtin/common/vector.lua:104: attempt to perform arithmetic on local 'b' (a nil value)
    07:35:53: ERROR[main]: stack traceback:
    07:35:53: ERROR[main]:  /usr/share/games/minetest/builtin/common/vector.lua:104: in function 'subtract'
    07:35:53: ERROR[main]:  ...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:139: in function 'node_detector_scan'
    07:35:53: ERROR[main]:  ...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:263: in function <...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:262>

I dont know how to reproduce it though.

Thanks!

**Comment by Jeija** [comment] 2015-02-16 19:17
That looks like a really weird bug to me.
It means that
```Lua
vector.subtract(pos, minetest.facedir_to_dir(node.param2))
```
fails, `attempt to perform arithmetic on local 'b' (a nil value)` indicates, that `minetest.facedir_to_dir(node.param2)'' returned nil. That means the facedir of your object detector must have been outside the range of possible param2 facedirs. If that is so, this could have been caused by some influence by other mods or by an engine bug.
If you or someone else can reproduce this bug, please tell me! Otherwise, I'll have to close this issue, because to me it doesn't seem like a mesecons bug.

**Comment by vitaminx** [comment] 2015-02-17 12:35
This is what I got from minetest developers:
"This is a bug in the mesecons mod, it calls subtract() with an invalid second parameter."

**Comment by Jeija** [comment] 2015-03-17 12:41
Since there is no map / etc. to reproduce this issue, I'm closing this now.

**Closed by Jeija** 2015-03-17 12:41 UTC
