### ISSUE TITLE
deSerialization problem, crash with command blocks

### ISSUE THREAD

**Issue by Megaf** [Jeija/minetest-mod-mesecons#232] opened 2015-04-14 20:56 UTC
I'm almost sure this is an engine(minetest) bug, but I will post it here so we can confirm that or not.

```
2015-04-14 16:42:59: ACTION[ServerThread]: Megaf leaves game. List of players: 
2015-04-14 16:43:01: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-04-14 16:43:01: ERROR[main]: ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:110: attempt to index a nil value
2015-04-14 16:43:01: ERROR[main]: stack traceback:
2015-04-14 16:43:01: ERROR[main]:       ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:110: in function 'resolve_commands'
2015-04-14 16:43:01: ERROR[main]:       ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:130: in function 'action_on'
2015-04-14 16:43:01: ERROR[main]:       .../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:189: in function <.../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:184>
2015-04-14 16:43:01: ERROR[main]:       ...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:90: in function 'execute'
2015-04-14 16:43:01: ERROR[main]:       ...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:84: in function <...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:61>
2015-04-14 16:43:01: ERROR[main]:       ...afServer/BinMegafServer/bin/../builtin/game/register.lua:341: in function <...afServer/BinMegafServer/bin/../builtin/game/register.lua:329>

In thread 7ffcb25bf760:
/home/minetest/MegafServer/SourceMegafServer/src/server.cpp:494: void Server::step(float): A fatal error occurred: ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:110: attempt to index a nil value
stack traceback:
        ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:110: in function 'resolve_commands'
        ...ods/minetest-mod-mesecons/mesecons_commandblock/init.lua:130: in function 'action_on'
        .../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:189: in function <.../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:184>
        ...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:90: in function 'execute'
        ...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:84: in function <...n/../mods/minetest-mod-mesecons/mesecons/actionqueue.lua:61>
        ...afServer/BinMegafServer/bin/../builtin/game/register.lua:341: in function <...afServer/BinMegafServer/bin/../builtin/game/register.lua:329>
Debug stacks:
DEBUG STACK FOR THREAD 7ffcaa525700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7ffcab137700:
#0  virtual void* CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 7ffcacd0c700:
#0  virtual void* ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  void Server::SendBlocks(float))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7ffcb25bf760:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)
Aborted
```

**Comment by Jeija** [comment] 2015-04-15 12:13
Looks like an engine bug to me, there has to be a player that lacks a `get_player_name()` function (or can players leave during execution of lua code?). Can you reproduce that bug somehow?

**Comment by Megaf** [comment] 2015-04-15 21:39
Hm, I was playing with a machine that used several commands blocks, I lagged a lot because of my internet and decided to leave, soon after I left the server crashed.

**Comment by Jeija** [comment] 2015-07-27 09:52
Assuming this is an engine bug, closing.

**Closed by Jeija** 2015-07-27 09:52 UTC
