### ISSUE TITLE
Doors problems

### ISSUE THREAD

**Issue by C1ffisme** [Jeija/minetest-mod-mesecons#220] opened 2015-02-12 21:08 UTC
I think I found a problem. I have the latest versions of mesecons and minetest (mostly), and the doors won't open when powered by mesecons. At first I thought that my steel doors wouldn't work because of protection, and then I found that wooden doors wouldn't work either. I want both doors to open again at a mesecon signal. Can this be fixed?

**Comment by cheapie** [comment] 2015-02-13 06:16
Do some thing like this: 

D
D
?
|

where D is the door (2m tall), ? is any node, and | is a vertical mesecon.

**Comment by C1ffisme** [comment] 2015-02-13 17:29
@cheapie It didn't work.

**Comment by MT-Modder** [comment] 2015-02-13 20:43
I think I figured out what the problem is. Place the door before placing the mesecon wires. The usual setup still works. The wires don't update after the door is placed. This is a weird bug.

**Comment by Jeija** [comment] 2015-02-13 21:52
I can confirm that, @MT-Modder.
The reason for this is simple: Mesecons updates the wires as soon as a node is placed that has some connection rules registered. That, however, is not the case with the doors: If a door is placed, you in fact only trigger a on_place on a craftitem that then manually calls set_node to "build up" the door.
The best way to fix this is to get minetest_game to use `minetest.place_node` in `doors/init.lua` instead of `minetest.set_node`, I will send them a pull request.

**Comment by MT-Modder** [comment] 2015-02-13 22:08
Awesome. The doors mod really needs to be rewritten. I would do it but pilzadam said he would.

**Comment by Jeija** [comment] 2015-02-13 22:49
Hmm, I just had a closer look at the issue. Doesn't look that great, because minetest.place_node just completely ignores any param2 given to it. So doors would connect to mesecons just fine, but their facedir will be messed up. A solution to this might be to keep using `minetest.set_node` and trigger on-place callbacks in `core.registered_on_placenodes` manually, but I have no idea if that is event possible, it certainly doesn't feel right.

**Comment by MT-Modder** [comment] 2015-02-13 23:18
I think it's possible but I've read it's not recommended as it would be called every time any node is placed instead of just when that specific node is. You've tested the minetest.place_node method? If it does ignore parameters in the node table then I would think this is a bug in the engine, no?

**Comment by MT-Modder** [comment] 2015-02-13 23:50
I just did some testing with ```minetest.place_node`` and got the same results as you. I'm going to submit an issue for the engine. This doesn't seem right IMO.

**Comment by MT-Modder** [comment] 2015-02-14 04:14
Okay I think the best solution to this problem would be to use one of the door nodes as the inventory item instead of a craftitem. This of course would require an entire rewrite of the doors mod.

**Comment by sofar** [comment] 2016-02-14 19:18
This can trivially be fixed by calling the on_place handlers. I'm investigating adding this to minetest_game.

**Comment by sofar** [comment] 2016-02-14 19:19
edit: this would be something that doors/init.lua does, no changes would be needed in mesecons.

**Comment by sofar** [comment] 2016-02-14 20:30
https://github.com/minetest/minetest_game/pull/852

**Comment by Jeija** [comment] 2016-02-21 13:02
Since https://github.com/minetest/minetest_game/pull/852 got merged, this issue is finally solved!

**Closed by Jeija** 2016-02-21 13:02 UTC
